In [1]:
import json
import pandas as pd

In [2]:
filename = 'uzair_tweets.jsonl'

In [4]:
data = []
with open(filename,encoding='utf-8') as f:
    for line in f:
        d = json.loads(line)
        good_columns = [d['created_at'], d['id'], d['lang'], d['full_text'], d['user']['verified'], d['user']['id'], 
                        d['user']['location'], d['entities']['hashtags'], d['geo']]
        data.append(good_columns)

In [5]:
good_column = ['created_at', 'id', 'lang', 'full_text', 'verified', 'author_id', 'user_loc', 'hashtags', 'tweet_loc']
df = pd.DataFrame(data, columns=good_column)

In [6]:
df.to_csv('march_tweets.csv', sep=',', index=False)

In [7]:
df.head()

,created_at,id,lang,full_text,verified,author_id,user_loc,hashtags,tweet_loc
0,Mon Mar 01 05:00:59 +0000 2021,1366252100242477057,en,Congrats to PM @narendramodi ji for taking #Co...,False,255873334,New Delhi,"[{'text': 'CoronaVaccine', 'indices': [43, 57]...",None
1,Mon Mar 01 05:01:00 +0000 2021,1366252104642224128,en,Did he really take it ??? Can somebody zoom an...,False,2496097650,BangaruTelangana,[],None
2,Mon Mar 01 05:01:00 +0000 2021,1366252105166692352,en,Today I called for Auckland to be prioritised ...,True,18149977,"Auckland, New Zealand",[],None
3,Mon Mar 01 05:01:00 +0000 2021,1366252105716097024,en,"""Coronaphobia"" is a new term that researchers ...",False,1159274155,,[],None
4,Mon Mar 01 05:01:01 +0000 2021,1366252110153662467,en,"In this viral and emotional TikTok, an ICU nur...",False,1159274155,,[],None

In [8]:
df.tail()

,created_at,id,lang,full_text,verified,author_id,user_loc,hashtags,tweet_loc
4817133,Thu Apr 01 04:01:32 +0000 2021,1377471164822421504,en,"ðŸš¨\nSecretary for the Civil Service, Patrick Ni...",False,27402457,Hong Kong,[],None
4817134,Thu Apr 01 04:01:28 +0000 2021,1377471148263280641,en,24th COVID-19 death reported in Grande Prairie...,False,50112241,"Grande Prairie, AB","[{'text': 'gpab', 'indices': [90, 95]}, {'text...",None
4817135,Thu Apr 01 04:01:11 +0000 2021,1377471078444855296,en,@JanJekielek @EpochTimes @realKTMcFarland This...,False,1366039025346252805,,"[{'text': 'BioweaponWarfare', 'indices': [50, ...",None
4817136,Thu Apr 01 04:01:52 +0000 2021,1377471250499579904,en,U.S. braces for possible surge in COVID cases ...,False,1353384031560339458,Maskup or covid is coming 4U,[],None
4817137,Thu Apr 01 04:01:15 +0000 2021,1377471093158539265,en,"Thread. \n\nWhen we mix science and politics, ...",False,14299276,Seattle,[],None

In [9]:
len(df[df.lang=='en'])

4817138